### PR TITLE
Update pyzabbix

### PR DESCRIPTION
**Pull request by paalbra**
There's a new version of pyzabbix with some tiny additions:

https://github.com/lukecyca/pyzabbix/compare/0.7.5...0.8.2

### CODE REVIEW

**Comment by mbakke** [comment]
I don't think we need to pin the version.  LGTM anyway, thanks!  :+1:

**Comment by paalbra** [comment]
It's advisable to always pin a major zero. At least if they follow semver https://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by mbakke** [comment]
I see, that makes sense.

**Comment by paalbra** [comment]
Removed version pinning in a new commit

**Pull request merged**
