### PR TITLE
Appease pylint and add validation tests

### PR DESCRIPTION
**Pull request by mbakke**
Inspired by #36 I ran pylint and fixed minor correctness problems.  Still plenty of warnings left though.

### CODE REVIEW

**Comment by paalbra** [comment]
I'm not sure the validator functions should be changed? They kind of look like static methods, but my belief is that they're different (that's why `cls` and not `self`. They receive a class and not a object, AFAIK).

Have you looked into this?

**Comment by mbakke** [comment]
Oh my, I had no idea.  I found that the validators were just silently ignored, presumably because of the type mismatch.

I updated the branch without that commit, and added tests for the validators to prevent shooting my foot again in the future.

Github is not updating this PR for some reason, but you can see the top two commits here: https://github.com/mbakke/zabbix-auto-config/commits/pylint

**Comment by paalbra** [comment]
I'm not sure that last commit was supposed to be added? It touches a different subject? https://github.com/unioslo/zabbix-auto-config/pull/38/commits/d7b3de8b772c0a0dedea1de4a8036c2b3ae19cf3

**Comment by mbakke** [comment]
I changed the subject to reflect the new situation.  Added it here mainly for convenience, but can submit it separately.

**Review by paalbra — APPROVED** [review]
👍

**Pull request merged**
